version: 2.1
jobs:
  # give any name to job
  4x-electron:
    # use Cypress built Docker image with Node 10 and npm 6
    docker:
      - image: cypress/base:10
    # tells CircleCI to execute this job on 4 machines simultaneously
    parallel: true # load balance all tests
    parallelism: 3
    group: '3x-electron on CircleCI' # name this group
    steps:
      - checkout
      # note: omitting caching for brevity
      # quickly install NPM dependencies
      - npm ci
      # load balance all tests across 4 CI machines
      - $(npm bin)/cypress run --parallel
